MAP_SWITCHING_MAPPING = {
   ["MountainPath"] = "Mountain Path",
   ["KeeperStronghold"] = "Keepers' Stronghold",
   ["KeeperTower"] = "Keepers' Stronghold",
   ["BlueCave"] = "Blue Caves",
   ["StrongholdDungeon"] = "Stronghold Dungeon",
   ["AncientWoods"] = "Ancient Woods",
   ["HorizonBeach"] = "Horizon Beach",
   ["SnowyPeaks"] = "Snowy Peaks",
   ["SunPalace"] = "Sun Palace",
   ["MagmaChamber"] = "Magma Chamber",
   ["MysticalWorkshop"] = "Mystical Workshop",
   ["Underworld"] = "The Underworld",
   ["AbandonedTower"] = "Abandoned Tower",
   ["BlobBurg"] = "Blob Burg",
   ["ForgottenWorld"] = "Forgotten World",
}