CHAMPION_LOCS = {
    "@Mountain Path - Monk/",
    "@Mountain Path #2/Mountain Path - Steam Golem",
    "@Blue Cave - Minitaur/",
    "@Blue Cave - Ascendant/",
    "@Blue Cave - Specter/Blue Cave - Specter",
    "@Stronghold Dungeon - Aazeraach/",
    "@Stronghold Dungeon - Beetloid/",
    "@Snowy Peaks/Snowy Peaks - Akhlut",
    "@Snowy Peaks - Dracozul/",
    "@Sun Palace - Diavola/",
    "@Sun Palace - Qilin/",
    "@Sun Palace - Kanko/",
    "@Ancient Woods - Goblin King/",
    "@Ancient Woods - Raduga/",
    "@Ancient Woods - Brutus/",
    "@Horizon Beach - Vodinoy/Horizon Beach - Vodinoy",
    "@Horizon Beach - Elderjel/Horizon Beach - Elderjel",
    "@Magma Chamber - Asura/",
    "@Magma Chamber - Gryphonix/Magma Chamber - Gryphonix",
    "@Underworld - Draconoir/Underworld - Draconoir",
    "@Underworld - Spinner/",
    "@Mystical Workshop - Goblin Pilot/",
    "@Mystical Workshop - Vertraag/",
    "@Blob Burg - King Blob/Blob Burg - King Blob",
    "@Forgotten World - Dracomer/",
    "@Forgotten World - Terradrile/",
    "@Abandoned Tower - Mad Lord/",
}